from server.lib.types import WebsiteCategory, LLMName

async def prompt_llm(prompt: str, llm_name: LLMName) -> str:
    ...


async def respond(category: WebsiteCategory) -> str:
    match category:
        case 'Computers and Technology':
            ...
        case 'Education':
            ...
        case 'Travel':
            ...
        case 'Sports':
            ...
        case 'E-Commerce':
            ...
        case 'Games':
            ...
        case 'Food':
            ...
        case 'News':
            ...
        case 'Health and Fitness':
            ...
        case 'Social Networking and Messaging':
            ...
        case _:
            raise ValueError(f'Unsupported category: "{category}"')