from server.lib.types import WebsiteCategory, LLMName, Conversation

async def _prompt_llm(prompt: str, llm_name: LLMName) -> str:
    ...


async def _get_prompt_for_category(category: WebsiteCategory) -> str:
    match category:
        case 'Computers and Technology':
            ...
        case 'Education':
            ...
        case 'Travel':
            ...
        case 'Sports':
            ...
        case 'E-Commerce':
            ...
        case 'Games':
            ...
        case 'Food':
            ...
        case 'News':
            ...
        case 'Health and Fitness':
            ...
        case 'Social Networking and Messaging':
            ...
        case _:
            raise ValueError(f'Unsupported category: "{category}"')


async def chat(conv: Conversation, html: str, category: WebsiteCategory) -> str:
    prompt_for_category = _get_prompt_for_category(category)