from server.lib.types import WebsiteCategory, Conversation, ModelName
from server.lib.utils import prompt_llm

async def _get_prompt_for_category(category: WebsiteCategory) -> str:
    # match category:
    #     case 'Computers and Technology':
    #         ...
    #     case 'Education':
    #         ...
    #     case 'Travel':
    #         ...
    #     case 'Sports':
    #         ...
    #     case 'E-Commerce':
    #         ...
    #     case 'Games':
    #         ...
    #     case 'Food':
    #         ...
    #     case 'News':
    #         ...
    #     case 'Health and Fitness':
    #         ...
    #     case 'Social Networking and Messaging':
    #         ...
    #     case _:
    #         raise ValueError(f'Unsupported category: '{category}'')
    return f'Website category: {category}'


async def chat(conv: Conversation, html: str, category: WebsiteCategory, model_name: ModelName) -> str:
    prompt_for_category = await _get_prompt_for_category(category)
    return await prompt_llm(prompt_for_category)